import { BRAND } from "@/lib/brand";

export type SeoLandingPage = {
  slug: string;
  title: string;
  description: string;
  h1: string;
  subtitle: string;
  collectionSlug?: string;
};

export const DISCOVER_PAGES: SeoLandingPage[] = [
  {
    slug: "chocolate-chip-cookies",
    title: "Best Chocolate Chip Cookies in Cairo | Cookie Bite",
    description: "Order the best freshly baked, thick and chewy chocolate chip cookies in Cairo. Premium ingredients and same-day delivery options available.",
    h1: "Freshly Baked Chocolate Chip Cookies",
    subtitle: "The classic you love, baked to perfection with premium Belgian chocolate.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "fresh-baked-cookies-cairo",
    title: "Fresh Baked Cookies Delivery in Cairo | Cookie Bite",
    description: "Craving fresh cookies? Cookie Bite delivers warm, gourmet stuffed cookies directly to your door in New Cairo and beyond.",
    h1: "Fresh Baked Cookies Delivered to You",
    subtitle: "Warm, gooey, and made from scratch. Explore our gourmet cookie menu.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "cookie-gift-boxes",
    title: "Gourmet Cookie Gift Boxes & Care Packages | Cookie Bite",
    description: "Send the perfect gift with our customizable cookie gift boxes. Perfect for birthdays, anniversaries, or corporate gifting in Egypt.",
    h1: "Gourmet Cookie Gift Boxes",
    subtitle: "The sweetest way to show you care. Build your own premium cookie box.",
  },
  {
    slug: "best-cookies-in-egypt",
    title: "Voted Best Cookies in Egypt | Premium Desserts",
    description: "Discover why Cookie Bite is loved across Egypt. Thick, chewy, and stuffed cookies baked fresh daily.",
    h1: "The Best Cookies in Egypt",
    subtitle: "Taste the difference of premium ingredients and artisanal baking.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "corporate-cookie-gifts",
    title: "Corporate Cookie Gifts & Client Appreciation | Cookie Bite",
    description: "Elevate your corporate gifting with premium branded cookie boxes. Perfect for events, holidays, and client appreciation in Cairo.",
    h1: "Corporate Cookie Gifting",
    subtitle: "Leave a lasting impression with customized, gourmet cookie boxes.",
  },
  {
    slug: "birthday-cookie-boxes",
    title: "Birthday Cookie Delivery | Alternative Birthday Cakes",
    description: "Celebrate birthdays with a box of freshly baked stuffed cookies instead of a traditional cake. Order delivery in New Cairo.",
    h1: "Birthday Cookie Boxes",
    subtitle: "Make their day sweeter with a box of their favorite gourmet cookies.",
  },
  {
    slug: "midnight-cookie-delivery",
    title: "Late Night Cookie Delivery New Cairo | Cookie Bite",
    description: "Satisfy your late-night cravings with Cookie Bite. Check our evening delivery hours for fresh cookies in New Cairo.",
    h1: "Late Night Cookie Cravings",
    subtitle: "We're here for your evening sweet tooth.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "gourmet-stuffed-cookies",
    title: "Gourmet Stuffed Cookies | Nutella, Lotus & More",
    description: "Indulge in our signature stuffed cookies. Featuring oozing Nutella, Lotus Biscoff, and Pistachio centers.",
    h1: "Signature Stuffed Cookies",
    subtitle: "Experience the ultimate cookie indulgence with our stuffed flavors.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "chewy-cookies-cairo",
    title: "Thick & Chewy NYC Style Cookies in Cairo | Cookie Bite",
    description: "Authentic New York style thick and chewy cookies, baked fresh in New Cairo. Order now for delivery.",
    h1: "Thick & Chewy Cookies",
    subtitle: "Crispy on the edges, soft and gooey in the center.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "premium-desserts-new-cairo",
    title: "Premium Desserts Delivery in New Cairo | Cookie Bite",
    description: "Looking for high-end desserts in New Cairo? Cookie Bite offers artisanal cookies baked with the finest ingredients.",
    h1: "Premium Desserts in New Cairo",
    subtitle: "Satisfy your sweet tooth with our artisanal cookie creations.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "custom-cookie-gifts",
    title: "Custom Cookie Gifts & Personalized Boxes",
    description: "Create a personalized cookie gift box for any occasion. Choose your flavors and add a custom message.",
    h1: "Personalized Cookie Gifts",
    subtitle: "Build the perfect custom box for someone special.",
  },
  {
    slug: "party-dessert-catering",
    title: "Party Dessert Catering & Events | Cookie Bite",
    description: "Cater your next party or event with Cookie Bite. Bulk cookie orders available for gatherings in Cairo.",
    h1: "Event & Party Catering",
    subtitle: "Make your event memorable with a stunning cookie display.",
  },
  {
    slug: "red-velvet-cookies",
    title: "Red Velvet Cookies Delivery | Cookie Bite",
    description: "Try our signature Red Velvet cookies, stuffed with premium cream cheese frosting. Baked fresh daily.",
    h1: "Red Velvet Cream Cheese Cookies",
    subtitle: "A decadent twist on a classic cake, transformed into a gooey cookie.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "double-chocolate-cookies",
    title: "Double Chocolate Fudge Cookies | Cookie Bite",
    description: "For the ultimate chocolate lover. Rich, fudgy double chocolate cookies made with premium cocoa.",
    h1: "Double Chocolate Fudge",
    subtitle: "Intensely chocolatey and incredibly fudgy.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "lotus-biscoff-cookies",
    title: "Lotus Biscoff Stuffed Cookies | Cookie Bite",
    description: "Our famous cookies stuffed with creamy Lotus Biscoff spread and topped with crushed biscuits.",
    h1: "Lotus Biscoff Stuffed Cookies",
    subtitle: "A caramelized biscuit dream in every bite.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "pistachio-stuffed-cookies",
    title: "Pistachio Stuffed Cookies Cairo | Cookie Bite",
    description: "Premium cookies generously stuffed with rich pistachio cream. A local favorite in New Cairo.",
    h1: "Pistachio Cream Stuffed",
    subtitle: "Rich, nutty, and irresistibly creamy.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "nutella-stuffed-cookies",
    title: "Nutella Stuffed Chocolate Chip Cookies | Cookie Bite",
    description: "The ultimate indulgence. Our classic chocolate chip cookie stuffed with oozing Nutella.",
    h1: "Nutella Stuffed Cookies",
    subtitle: "Your favorite cookie with a molten chocolate-hazelnut center.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "cookie-boxes-for-events",
    title: "Cookie Boxes for Events & Weddings | Cookie Bite",
    description: "Beautifully packaged cookie boxes for weddings, corporate events, and large gatherings in Egypt.",
    h1: "Event Cookie Boxes",
    subtitle: "Sweeten your special day with our catering boxes.",
  },
  {
    slug: "graduation-cookie-gifts",
    title: "Graduation Cookie Gift Boxes | Cookie Bite",
    description: "Celebrate their big achievement with a premium box of Cookie Bite's finest stuffed cookies.",
    h1: "Graduation Cookie Gifts",
    subtitle: "Say congratulations with the best cookies in town.",
  },
  {
    slug: "anniversary-dessert-boxes",
    title: "Anniversary Dessert Boxes | Cookie Bite",
    description: "Surprise your loved one with a romantic dessert box of our signature gourmet cookies.",
    h1: "Anniversary Dessert Boxes",
    subtitle: "A sweet celebration of your special milestone.",
  },
  {
    slug: "care-package-cookies",
    title: "Send a Cookie Care Package | Cookie Bite",
    description: "Brighten someone's day by sending a freshly baked cookie care package anywhere in our delivery zones.",
    h1: "Cookie Care Packages",
    subtitle: "Send a warm hug in the form of a cookie box.",
  },
  {
    slug: "holiday-cookie-gifts",
    title: "Holiday & Christmas Cookie Gifts | Cookie Bite",
    description: "Seasonal holiday cookie boxes and festive flavors. The perfect gift for family, friends, and clients.",
    h1: "Holiday Cookie Gifts",
    subtitle: "Spread festive cheer with our limited edition holiday boxes.",
  },
  {
    slug: "artisan-cookies-egypt",
    title: "Artisan Handcrafted Cookies in Egypt | Cookie Bite",
    description: "Every Cookie Bite cookie is handcrafted with care using the finest ingredients for an artisan bakery experience.",
    h1: "Artisan Handcrafted Cookies",
    subtitle: "Baked with passion, served with love.",
    collectionSlug: "all-cookies",
  },
];

export const DISTRICT_PAGES: SeoLandingPage[] = [
  {
    slug: "new-cairo",
    title: "Cookie Delivery in New Cairo | Cookie Bite",
    description: "Fast and fresh cookie delivery across New Cairo. Order gourmet stuffed cookies directly to your compound.",
    h1: "Cookie Delivery in New Cairo",
    subtitle: "Freshly baked cookies delivered to your door in New Cairo.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "fifth-settlement",
    title: "Cookie Delivery in Fifth Settlement (Tagamoa) | Cookie Bite",
    description: "Craving cookies in Tagamoa? We deliver warm, freshly baked cookies across the Fifth Settlement.",
    h1: "Cookie Delivery in Fifth Settlement",
    subtitle: "Your favorite cookies, delivered in Tagamoa.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "rehab-city",
    title: "Cookie Delivery in Al Rehab City | Cookie Bite",
    description: "Order premium cookies for delivery to Al Rehab City. Perfect for gifting or treating yourself.",
    h1: "Cookie Delivery in Rehab City",
    subtitle: "Bringing sweetness to Al Rehab, one box at a time.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "madinaty",
    title: "Cookie Delivery in Madinaty | Cookie Bite",
    description: "Yes, we deliver to Madinaty! Order our signature stuffed cookies for fresh delivery to your home.",
    h1: "Cookie Delivery in Madinaty",
    subtitle: "Gourmet cookies delivered fresh to Madinaty.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "mivida",
    title: "Cookie Delivery in Mivida Compound | Cookie Bite",
    description: "Specialized delivery to Mivida Compound. Order the best chocolate chip cookies straight to your door.",
    h1: "Cookie Delivery to Mivida",
    subtitle: "Premium cookies for our Mivida neighbors.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "mountain-view",
    title: "Cookie Delivery in Mountain View | Cookie Bite",
    description: "Enjoy fast cookie delivery to Mountain View compounds. The perfect treat for any occasion.",
    h1: "Cookie Delivery to Mountain View",
    subtitle: "Freshly baked sweetness delivered to your compound.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "hyde-park",
    title: "Cookie Delivery in Hyde Park New Cairo | Cookie Bite",
    description: "We deliver our freshly baked cookies directly to Hyde Park. Order your customized box today.",
    h1: "Cookie Delivery to Hyde Park",
    subtitle: "Gourmet cookie boxes delivered to Hyde Park.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "katameya-heights",
    title: "Cookie Delivery in Katameya Heights | Cookie Bite",
    description: "Premium cookie catering and delivery to Katameya Heights. Order luxury dessert boxes.",
    h1: "Cookie Delivery to Katameya",
    subtitle: "Luxury dessert delivery for Katameya residents.",
    collectionSlug: "all-cookies",
  },
  {
    slug: "heliopolis",
    title: "Cookie Delivery in Heliopolis & Sheraton | Cookie Bite",
    description: "We offer scheduled cookie deliveries to Heliopolis and Sheraton. Check our delivery days and order now.",
    h1: "Cookie Delivery in Heliopolis",
    subtitle: "Scheduled fresh deliveries to Heliopolis & Sheraton.",
    collectionSlug: "all-cookies",
  },
];
