/** قائمة مختصرة للإكمال التلقائي — يمكن توسيعها لاحقاً من API جغرافي */
export const EGYPT_CITIES: readonly string[] = [
  "Cairo",
  "Giza",
  "Alexandria",
  "Shubra El Kheima",
  "Port Said",
  "Suez",
  "Luxor",
  "Mansoura",
  "El Mahalla El Kubra",
  "Tanta",
  "Asyut",
  "Ismailia",
  "Faiyum",
  "Zagazig",
  "Aswan",
  "Damietta",
  "Damanhur",
  "Minya",
  "Beni Suef",
  "Qena",
  "Sohag",
  "Hurghada",
  "Sharm El Sheikh",
  "New Cairo",
  "6th of October City",
  "Sheikh Zayed",
  "Nasr City",
  "Heliopolis",
  "Maadi",
  "Zamalek",
  "Obour City",
  "Badr City",
  "10th of Ramadan City",
  "Sadat City",
  "New Administrative Capital",
  "Qalyub",
  "Banha",
  "Kafr El Sheikh",
  "Desouk",
  "Mallawi",
  "Benha",
  "Arish",
  "Safaga",
  "Marsa Matruh",
  "El Gouna",
  "North Coast",
  "Ain Sokhna",
  "Ras Sudr",
  "El Minya",
  "Kom Ombo",
  "Edfu",
  "Esna",
] as const;

export function filterEgyptCities(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...EGYPT_CITIES].slice(0, limit);
  return EGYPT_CITIES.filter((c) => c.toLowerCase().includes(q)).slice(0, limit);
}
