#!/usr/bin/env node
/**
 * Prepare cookie-bite-python for local or production use.
 * - Ensures INTERNAL_API_SECRET + PYTHON_API_URL in root .env
 * - Writes cookie-bite-python/.env from Next.js env (never prints secrets)
 *
 * Usage: npm run python:setup
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pyDir = resolve(root, "cookie-bite-python");
const pyEnvPath = resolve(pyDir, ".env");

const ROOT_KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_KEY",
  "INTERNAL_API_SECRET",
  "NEXT_PUBLIC_APP_URL",
  "APP_BASE_URL",
  "DATABASE_URL",
  "SUPABASE_DATABASE_URL",
  "CLERK_JWKS_URL",
  "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
];

function loadEnvFile(file) {
  const p = resolve(root, file);
  if (!existsSync(p)) return {};
  const out = {};
  for (const line of readFileSync(p, "utf8").split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 0) continue;
    const k = t.slice(0, i).trim();
    const v = t.slice(i + 1).trim().replace(/^["']|["']$/g, "");
    out[k] = v;
  }
  return out;
}

function upsertRootEnv(key, value) {
  const p = resolve(root, ".env");
  let content = existsSync(p) ? readFileSync(p, "utf8") : "";
  const re = new RegExp(`^${key}=.*$`, "m");
  const line = `${key}=${value}`;
  if (re.test(content)) {
    content = content.replace(re, line);
  } else {
    if (content && !content.endsWith("\n")) content += "\n";
    content += `\n# Python microservices (npm run python:setup)\n${line}\n`;
  }
  writeFileSync(p, content, "utf8");
}

function inferClerkJwks(env) {
  if (env.CLERK_JWKS_URL?.trim()) return env.CLERK_JWKS_URL.trim();
  // Production custom domain used by this project
  return "https://clerk.cookie-bite.com/.well-known/jwks.json";
}

function inferDatabaseUrl(env) {
  return (
    env.DATABASE_URL?.trim() ||
    env.SUPABASE_DATABASE_URL?.trim() ||
    env.SUPABASE_DB_URL?.trim() ||
    ""
  );
}

function inferAllowedOrigins(env) {
  const origins = new Set(["http://localhost:3000", "http://127.0.0.1:3000"]);
  for (const k of ["NEXT_PUBLIC_APP_URL", "APP_BASE_URL"]) {
    const v = env[k]?.trim().replace(/\/$/, "");
    if (v) origins.add(v);
  }
  origins.add("https://cookie-bite.com");
  origins.add("https://www.cookie-bite.com");
  return [...origins].join(",");
}

const rootEnv = { ...loadEnvFile(".env"), ...loadEnvFile(".env.local") };

if (!rootEnv.INTERNAL_API_SECRET?.trim()) {
  const secret = randomBytes(32).toString("hex");
  upsertRootEnv("INTERNAL_API_SECRET", secret);
  rootEnv.INTERNAL_API_SECRET = secret;
  console.log("Added INTERNAL_API_SECRET to .env");
}

if (!rootEnv.PYTHON_API_URL?.trim()) {
  upsertRootEnv("PYTHON_API_URL", "http://127.0.0.1:8000");
  rootEnv.PYTHON_API_URL = "http://127.0.0.1:8000";
  console.log("Added PYTHON_API_URL=http://127.0.0.1:8000 to .env");
}

const databaseUrl = inferDatabaseUrl(rootEnv);
const supabaseUrl = rootEnv.NEXT_PUBLIC_SUPABASE_URL?.trim() ?? "";
const anonKey = rootEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() ?? "";
const serviceKey = rootEnv.SUPABASE_SERVICE_KEY?.trim() ?? "";
const internalSecret = rootEnv.INTERNAL_API_SECRET?.trim() ?? "";

const missing = [];
if (!supabaseUrl) missing.push("NEXT_PUBLIC_SUPABASE_URL");
if (!anonKey) missing.push("NEXT_PUBLIC_SUPABASE_ANON_KEY");
if (!serviceKey) missing.push("SUPABASE_SERVICE_KEY");
if (!internalSecret) missing.push("INTERNAL_API_SECRET");
if (!databaseUrl) missing.push("DATABASE_URL (Supabase → Database → URI)");

const pyLines = [
  "# Auto-generated by npm run python:setup — edit DATABASE_URL if needed",
  "APP_ENV=development",
  `SECRET_KEY=${randomBytes(16).toString("hex")}`,
  "",
  `SUPABASE_URL=${supabaseUrl}`,
  `SUPABASE_ANON_KEY=${anonKey}`,
  `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}`,
  databaseUrl
    ? `DATABASE_URL=${databaseUrl}`
    : "# DATABASE_URL=postgresql://postgres:PASSWORD@db.PROJECT.supabase.co:5432/postgres",
  "",
  "REDIS_URL=redis://127.0.0.1:6379/0",
  "",
  `INTERNAL_API_SECRET=${internalSecret}`,
  `CLERK_JWKS_URL=${inferClerkJwks(rootEnv)}`,
  `ALLOWED_ORIGINS=${inferAllowedOrigins(rootEnv)}`,
  "",
];

writeFileSync(pyEnvPath, pyLines.join("\n"), "utf8");
console.log(`Wrote ${pyEnvPath}`);

if (missing.length) {
  console.warn("\n⚠ Missing in root .env — fill these then re-run npm run python:setup:");
  for (const m of missing) console.warn(`  - ${m}`);
  console.warn("\nDATABASE_URL: Supabase Dashboard → Project Settings → Database → Connection string (URI)");
  process.exit(1);
}

console.log(`
Next steps (local):
  1. npm run python:up          # Docker: API on :8000 + Redis
  2. curl http://127.0.0.1:8000/health
  3. Restart Next.js (npm run dev) so PYTHON_API_URL is loaded
  4. npm run python:retrain     # optional — refresh ML models

Production (Hostinger + Python):
  - Host Next.js on Hostinger as today
  - Run Python API on a VPS / Railway / Render (port 8000, same docker compose)
  - Set PYTHON_API_URL=https://your-python-host in hPanel env
  - Use the same INTERNAL_API_SECRET in both Next and Python .env
  - Add PYTHON_API_URL to npm run hostinger:env-audit import file

Verify on site:
  - /shop → "Trending" section uses ML when Python responds
  - Homepage → "For you" rail
  - Admin import PDF needs Python running
`);
