import type { ModuleImportExportConfig } from "@/lib/admin/import-export/types";
import type { ModuleKey } from "@/lib/admin/rbac";

const base = (partial: ModuleImportExportConfig): ModuleImportExportConfig => partial;

export const MODULE_IMPORT_EXPORT_REGISTRY: Record<ModuleKey, ModuleImportExportConfig> = {
  dashboard: base({
    module: "dashboard",
    label: "Dashboard",
    importEnabled: false,
    exportEnabled: false,
    templateColumns: [],
    exportColumns: [],
    maxImportRows: 0,
  }),
  products: base({
    module: "products",
    label: "Products",
    table: "products",
    importEnabled: true,
    exportEnabled: true,
    maxImportRows: 500,
    templateColumns: [
      { key: "id", label: "ID (UUID)", required: true },
      { key: "slug", label: "Slug" },
      { key: "name", label: "Name" },
      { key: "title_en", label: "Title EN" },
      { key: "sku", label: "SKU" },
      { key: "category", label: "Category" },
      { key: "price_egp", label: "Price EGP" },
      { key: "stock", label: "Stock" },
      { key: "is_active", label: "Active (true/false)" },
    ],
    exportColumns: [
      "id",
      "slug",
      "name",
      "title_en",
      "title_ar",
      "sku",
      "category",
      "price_egp",
      "compare_price_egp",
      "stock",
      "is_active",
      "created_at",
      "updated_at",
    ],
  }),
  addons: base({
    module: "addons",
    label: "Add-ons",
    table: "addons",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: ["id", "name", "type", "required", "is_active", "created_at", "updated_at"],
  }),
  orders: base({
    module: "orders",
    label: "Orders",
    table: "orders",
    importEnabled: true,
    exportEnabled: true,
    maxImportRows: 500,
    templateColumns: [
      { key: "id", label: "Order ID (UUID)", required: true },
      { key: "status", label: "Status (pending/processing/shipped/delivered/cancelled/refunded)" },
      { key: "payment_status", label: "Payment status (unpaid/paid/failed/refunded)" },
    ],
    exportColumns: [
      "id",
      "order_code",
      "order_number",
      "status",
      "payment_status",
      "payment_method",
      "total_egp",
      "subtotal_egp",
      "delivery_fee_egp",
      "discount_amount_egp",
      "guest_email",
      "created_at",
      "updated_at",
    ],
  }),
  customers: base({
    module: "customers",
    label: "Customers",
    table: "users",
    importEnabled: true,
    exportEnabled: true,
    maxImportRows: 500,
    templateColumns: [
      { key: "email", label: "Email", required: true },
      { key: "full_name", label: "Full name" },
      { key: "phone", label: "Phone" },
      { key: "points", label: "Loyalty points" },
    ],
    exportColumns: [
      "id",
      "email",
      "full_name",
      "phone",
      "phone_secondary",
      "points",
      "role",
      "profile_notes",
      "created_at",
      "updated_at",
    ],
  }),
  discounts: base({
    module: "discounts",
    label: "Discounts",
    table: "promo_codes",
    importEnabled: true,
    exportEnabled: true,
    maxImportRows: 200,
    templateColumns: [
      { key: "code", label: "Code", required: true },
      { key: "type", label: "Type (percent/fixed)", required: true },
      { key: "value", label: "Value", required: true },
      { key: "min_order_amount_egp", label: "Min order EGP" },
      { key: "max_uses", label: "Max uses" },
      { key: "is_active", label: "Active (true/false)" },
    ],
    exportColumns: [
      "id",
      "code",
      "type",
      "value",
      "min_order_amount_egp",
      "max_uses",
      "used_count",
      "is_active",
      "valid_until",
      "created_at",
    ],
  }),
  media: base({
    module: "media",
    label: "Media",
    importEnabled: false,
    exportEnabled: false,
    templateColumns: [],
    exportColumns: [],
    maxImportRows: 0,
  }),
  cms: base({
    module: "cms",
    label: "CMS",
    importEnabled: false,
    exportEnabled: false,
    templateColumns: [],
    exportColumns: [],
    maxImportRows: 0,
  }),
  templates: base({
    module: "templates",
    label: "Templates",
    table: "notification_templates",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: ["id", "channel", "key", "language", "subject", "is_active"],
  }),
  analytics: base({
    module: "analytics",
    label: "Reports",
    table: "orders",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: ["id", "order_code", "status", "payment_status", "total_egp", "created_at"],
  }),
  financial: base({
    module: "financial",
    label: "Financial",
    table: "expenses",
    importEnabled: true,
    exportEnabled: true,
    maxImportRows: 200,
    templateColumns: [
      { key: "title", label: "Title", required: true },
      { key: "category", label: "Category" },
      { key: "amount_egp", label: "Amount EGP", required: true },
      { key: "expense_date", label: "Date (YYYY-MM-DD)" },
    ],
    exportColumns: ["id", "title", "category", "amount_egp", "expense_date", "created_at"],
  }),
  invoices: base({
    module: "invoices",
    label: "Invoices",
    table: "invoices",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: ["id", "invoice_number", "order_id", "status", "total_egp", "created_at"],
  }),
  shipping: base({
    module: "shipping",
    label: "Shipping",
    table: "shipping_zones",
    importEnabled: true,
    exportEnabled: true,
    maxImportRows: 100,
    templateColumns: [
      { key: "name", label: "Zone name", required: true },
      { key: "base_fee_egp", label: "Base fee EGP" },
      { key: "is_active", label: "Active" },
    ],
    exportColumns: [
      "id",
      "name",
      "base_fee_egp",
      "free_shipping_threshold_egp",
      "eta_min_days",
      "eta_max_days",
      "is_active",
      "center_lat",
      "center_lng",
      "radius_km",
      "sort_order",
      "created_at",
    ],
  }),
  payments: base({
    module: "payments",
    label: "Payments",
    table: "payments",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: ["id", "order_id", "amount_egp", "status", "provider", "created_at"],
  }),
  roles: base({
    module: "roles",
    label: "Roles",
    table: "users",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: ["id", "email", "role", "full_name", "created_at"],
  }),
  settings: base({
    module: "settings",
    label: "Settings",
    importEnabled: false,
    exportEnabled: false,
    templateColumns: [],
    exportColumns: [],
    maxImportRows: 0,
  }),
  audit: base({
    module: "audit",
    label: "Audit",
    table: "audit_logs",
    importEnabled: false,
    exportEnabled: true,
    maxImportRows: 0,
    templateColumns: [],
    exportColumns: [
      "id",
      "created_at",
      "actor_email",
      "actor_role",
      "action",
      "module",
      "entity_id",
      "ip",
      "user_agent",
    ],
  }),
};

export function getModuleConfig(module: string): ModuleImportExportConfig | null {
  if (module in MODULE_IMPORT_EXPORT_REGISTRY) {
    return MODULE_IMPORT_EXPORT_REGISTRY[module as ModuleKey];
  }
  return null;
}

export function isValidImportExportModule(module: string): module is ModuleKey {
  return module in MODULE_IMPORT_EXPORT_REGISTRY;
}
